// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_wkcq3H29zBtCOoJQ3YXucM7Q2iobn_I',
    appId: '1:245198768205:web:739de1ad48e830dc953404',
    messagingSenderId: '245198768205',
    projectId: 'velitas-tp3final',
    authDomain: 'velitas-tp3final.firebaseapp.com',
    storageBucket: 'velitas-tp3final.appspot.com',
    measurementId: 'G-7060F9FTTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtS17DYKJZUeDEl9WRAyB7-99SDKS3TE',
    appId: '1:245198768205:android:f30a4897c7d0f88e953404',
    messagingSenderId: '245198768205',
    projectId: 'velitas-tp3final',
    storageBucket: 'velitas-tp3final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUA4PYmIeTmLdB1igo8nA5XM7rvcdIJs',
    appId: '1:245198768205:ios:5e1034811c71453d953404',
    messagingSenderId: '245198768205',
    projectId: 'velitas-tp3final',
    storageBucket: 'velitas-tp3final.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQUA4PYmIeTmLdB1igo8nA5XM7rvcdIJs',
    appId: '1:245198768205:ios:5e1034811c71453d953404',
    messagingSenderId: '245198768205',
    projectId: 'velitas-tp3final',
    storageBucket: 'velitas-tp3final.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_wkcq3H29zBtCOoJQ3YXucM7Q2iobn_I',
    appId: '1:245198768205:web:f15550c7fbd62729953404',
    messagingSenderId: '245198768205',
    projectId: 'velitas-tp3final',
    authDomain: 'velitas-tp3final.firebaseapp.com',
    storageBucket: 'velitas-tp3final.appspot.com',
    measurementId: 'G-NC0SQ8STGM',
  );

}